### ISSUE TITLE
[FEAT] Photo 구현

### ISSUE THREAD

**Issue by daehwan2yo** [Team-SpoonClass/BE#35]
## 🤗 구현하는 기능

Photo 관련 기능 구현

## 😳 목표 기간 

~21/11/23

## 😤  To-do

- [ ] Photo 자식 class 구체화
- [ ] Photo API 구성
- [ ] Photo Service 구현

## 😋 참고사항

feature/photo
