### ISSUE TITLE
[FEAT] Lesson이 열렸는지 닫혔는지 구분하는 타입 추가

### ISSUE THREAD

**Issue by daehwan2yo** [Team-SpoonClass/BE#45]
## 🤗 구현하는 기능

LessonStatus Enum을 추가한다.
- api 와 service에도 맞춰서 수정한다.

## 😳 목표 기간 

~21/11/29

## 😤  To-do

- [x] LessonStatus Enum 추가
- [x] API Response 추가
- [x] Service 에 추가
- [x] Rest Docs 반영

## 😋 참고사항

feature/lesson
